### ISSUE TITLE
Spherical, Capsule, Planar Limits - small enhancement request

### ISSUE THREAD

**Issue by oivio** [pafuhana1213/KawaiiPhysics#5]
Currently **Spherical, Capsule, Planar Limits** Offset Location and Rotation can be driving only by bone. 
My enhancement request is being able to set them as well in "**External Force**" or maybe keep it in same place. This will help to interact with the outside forces.

To show that idea I did create picture with photoshop. 

![kawaii](https://user-images.githubusercontent.com/38628851/67203567-bb8e6600-f40b-11e9-86c7-a0f7642cfc7e.jpg)

ありがとうございました

**Comment by pafuhana1213** [comment]
Hi oivio!

Do you want to apply different external forces for each bone?
I may not understand your request correctly so I want to know more specific use cases.

Thanks

**Comment by oivio** [comment]
It does not have to be as "External Force" It could be kept at "Spherical, Capsule, Planar Limits" tabs. Just to have the ability to set visibility of pin location and rotation of does limit.
But I did find some other way of doing it. Currently, I did create "virtual bone". Before applying kawaii physics I do set location and rotation of that "virtual bone" and then I do use this "virtual bone" in "sphere limits".   As for example: 
![kawaii2](https://user-images.githubusercontent.com/38628851/67405183-b3255f00-f5b4-11e9-91cf-2940de3c853f.jpg)

**Comment by pafuhana1213** [comment]
Does it mean that you want to control with AnimationBP variables by publishing to AnimNode pins?
Since it is not possible to expose only OffsetLocation and Rotation to the pin in the AnimGraph specification, it looks like the following image.
![image](https://user-images.githubusercontent.com/8957600/67416218-69169a80-f601-11e9-8bf4-0604d334a743.png)

It was like this during development, but because it was very inefficient, it was omitted.I forgot the details, but the main reason is the risk of iterating and resetting properties such as previews and parameter updates. So unfortunately I'm not aggressive about your request.

If you are interested this, try to add meta = (PinHiddenByDefault) to UPROPERTY of SphericalLimits, CapsuleLimits, PlanarLimits, and add BlueprintType to USTRUCT of FSphericalLimit, FCapsuleLimit, FPlanarLimit.

Personally, I think your workflow that uses your virtual bones is the best.

**Comment by oivio** [comment]
Few days ago I did actually manage to use "meta = (PinHiddenByDefault)" but, for the same reason, as you did say "I did not use it. it was very inefficient" That's why I ask for a request. So, in the meanwhile, I did find workflow with "virtual bone". 

Thank you for answering and I wish you to have a great day.

ありがとうございました
