### ISSUE TITLE
UE5.1 Crashes when spinning the second capsule collide

### ISSUE THREAD

**Issue by SC068** [pafuhana1213/KawaiiPhysics#86]
The second collider is not displayed,When I reopen the Animation Blueprint, it worked.but when I spinning it,my unreal engine was crashed.

**Comment by gotgrassct** [comment]
I second this, whenever I rotate a capsule collider or I think any collider, it just crashes. This is for 5.1. It's really frustrating working with the collisions cause it always crashes.

**Comment by ruminaire** [comment]
I thought it's only my AnimBP which has some problem, it's starting crash often when changing any collider/collision. Now I think it's only happen start in 5.1

My workaround for now is whenever I make changes to collider, I make sure to save my blueprint first, then click on empty space (de-select KawaiiPhysics node I'm currently working on so there's no KawaiiPhysics visual debug active), only then I press compile and pray it doesn't crash.

More often it works. sometimes it still crash the engine, but since I already saved my progress, next time I opened the engine my AnimBP is compiled fine (how? why? idk), it's slow workaround and very frustrating when I'm trying to change many nodes this way.

Also could confirm if I add new collider like @SC068 said, it won't displayed until I reopen AnimBP.

**Comment by pafuhana1213** [comment]
Hi guys,
Sorry for my late reply, and thanks for your feedback!

I can't reproduce the crash reported by @ruminaire but I have fixed the issue reported by @SC068 .
https://github.com/pafuhana1213/KawaiiPhysics/commit/4268a480969b0ee9964620ff4c6366ff8eab8457

I believe @ruminaire's crash has been resolved as we've made a lot of improvements to the collider preview, but if it happens again, please provide the error log, call stack, and steps to reproduce.

Thanks!

**Comment by gotgrassct** [comment]
When will the update release?

**Comment by pafuhana1213** [comment]
Hi guys,
Perhaps this fix should have solved the crash when editing Rotation
https://github.com/pafuhana1213/KawaiiPhysics/commit/09febed1feca4ff48882cfaa6212fd76c3106a1c

**Comment by pafuhana1213** [comment]
@gotgrassct 
maybe soon ;)

**Comment by gotgrassct** [comment]
Awesome, do you think maybe later today? (5/14)

**Comment by SC068** [comment]
@pafuhana1213 I tried it and it worked correctly! Thank you very much to solve this problem!
